swagger: '2.0'
info:
  title: Sunglasses API
  description: For access to Sunglasses.io data.
  version: 1.0.0
host:
schemes:
  - https
produces:
  - application/json
paths:
  /products:
    get:
      summary: Products
      description: |
        The Products endpoint allows you to search all products
      parameters:
        - name: query
          in: query
          description: Search query string
          required: false
          type: string
      tags:
        - Products
      responses:
        '200':
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /brands:
    get:
      summary: Brands
      description: |
        The Brands endpoint allows you to search all brands
      tags:
        - Brands
      responses:
        '200':
          description: Array of brands and brand IDs
          schema:
            $ref: '#/definitions/Brand'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /brands/{brandId}/products:
    get:
      summary: Products on a specific brand
      description: |
        This endpoint allows you search products of a specified brand
      parameters:
        - name: brandId
          in: path
          description: The id of a specific brand
          required: true
          type: string
      tags:
        - Brands
      responses:
        '200':
          description: An array of products
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /login:
    post:
      summary: User Login
      description: |
        This endpoint allows an authorized user to login and gain access to their cart
      tags:
        - User
      responses:
        '200':
          description: An array of users
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /me/cart:
    get:
      summary: Cart of logged in User
      description: >-
        The Cart GET endpoint returns information regarding the authorized User's cart's current contents
      tags:
        - User
      responses:
        '200':
          description: An array of products
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Edit quantities of items in cart
      description: |
        This Cart POST endpoint allows you to edit the quantity of the items in the cart
      tags:
        - User
      responses:
        '200':
          description: Product quantity successfully updated
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /me/cart/{productId}:
    post:
      summary: Add a product to cart
      description: |
        This endpoint allows you to add a product to the authorized user's cart
      parameters:
        - name: productId
          in: path
          description: The id of the product to add
          required: true
          type: string
      tags:
        - User
      responses:
        '200':
          description: Product successfully added to the cart
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Remove a product from cart
      description: |
        This endpoint allows you to remove a product from the authorized user's cart
      parameters:
        - name: productId
          in: path
          description: The id of the product to delete
          required: true
          type: string
      tags:
        - User
      responses:
        '200':
          description: Product successfully removed from the cart
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Product:
    type: object
    properties:
      productId:
        type: string
        description: Unique identifier for a product
      brandId:
        type: string
        description: ID of the brand
      title:
        type: string
        description: The name of this product
      description:
        type: string
        description: Description of the product
      price:
        type: integer
        description: The price of this product
      imageUrls:
        type: array
        description: An array of this product's sample images
        items:
          type: string
  Brand:
    type: object
    properties:
      brandId:
        type: string
        description: ID of the brand
      brand_name:
        type: string
        description: Name of the brand
  User:
    type: object
    properties:
      gender:
        type: string
        description: User's gender
      cart:
        type: array
        items:
          type: object
        description: User's cart
      name:
        type: object
        description: Object containing the User's title, first, and last name.
        properties:
          title:
            type: string
          first:
            type: string
          last:
            type: string
      location:
        type: object
        description: User's physical location
        properties:
          street:
            type: string
          city:
            type: string
          state:
            type: string
          postcode:
            type: integer
      email:
        type: string
        description: User's email address
      login:
        type: object
        description: User's login info
        properties:
          username:
            type: string
          password:
            type: string
          salt:
            type: string
          md5:
            type: string
          sha1:
            type: string
          sha256:
            type: string
      dob:
        type: string
        description: User's date of birth
      registered:
        type: string
        description: Date and time the User registered
      phone:
        type: string
        description: User's phone number
      cell:
        type: string
        description: User's cell phone number
      picture:
        type: object
        description: Object containing thumbnail, medium, and large User avatar URLs
        properties:
          large:
            type: string
          medium:
            type: string
          thumbnail:
            type: string
      nat:
        type: string
        description: User's nationality
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
